/*
******************************           DO NOT EDIT THIS FILE!!!           				*********************************
******************************         Please edit CustomRelation.java instead!        		*********************************	
******************************         不要编辑这个文件，这个文件每次都会被机器人覆盖!!!              *********************************
******************************    CustomRelation.java专门用于定制，该文件存在的时候不会被覆盖      	*********************************


*/
package com.youbenben.youbenben;
import java.util.HashMap;
import java.util.Map;

public class BaseRelation{

	
	Map<String, String> relationMapping ;
	
	public String getRelation(String fromType, String fromId, String targetField, String targetId)
	{
		//the entry for external calls, ugly code with many path just works, using a map is fine but lose the way to override the methods
		
		if(relationMapping == null){
			prepareRelation();
		}

		String key = fromType+"->"+targetField;
		
		String relation = relationMapping.get(key);
		if(relation == null){
			throw new IllegalArgumentException("Not able to find any relation to the target type: "+ targetField);
		}
		return relation;
		
	}
	
	protected void addGenericRelation(String fromType, String relation,String targetField)
	{
		if(relationMapping == null){
			relationMapping = new HashMap<String,String>();
		}
		String key = fromType.trim()+"->"+targetField.trim();
		relationMapping.put(key, relation);
	}
	protected void replaceGenericRelation(String fromType, String relation,String targetField)
	{
		addGenericRelation( fromType, relation, targetField );
	}
	
	
	
	Map<String, String[]> relationIndex ;
	protected void addRelationIndex(String fromType,String related[])
	{
		if(relationIndex == null){
			relationIndex = new HashMap<String,String[]>();
		}
		
		relationIndex.put(fromType, related);
	}
	protected void replaceRelationIndex(String fromType,String related[])
	{
		addRelationIndex( fromType, related);
	}
	
	public String getTableFieldName(String expr){
		//the expr looks like owner:DecorationAccelerator
		String[] splitedValues = expr.split(":");
		if(splitedValues.length < 1){
			throw new IllegalArgumentException("Not able to split expr: "+expr);
		}
		
		return splitedValues[0];
	}
	public String getBeanFieldName(String expr){
		//the expr looks like owner:DecorationAccelerator
		String[] splitedValues = getTableFieldName(expr).split("_");
		String ret = splitedValues[0];
		for(int i=1;i<splitedValues.length;i++){
			
			ret = ret+splitedValues[i].substring(0,1).toUpperCase()+splitedValues[i].substring(1);
			
		}
		
		return ret;
	}
	public String getFieldType(String expr){
		//the expr looks like owner:DecorationAccelerator
		String[] splitedValues = expr.split(":");
		if(splitedValues.length < 2){
			throw new IllegalArgumentException("Not able to split expr: "+expr);
		}
		
		return splitedValues[1];
	}
	public String [] getRelationIndex(String type){
		
		if(relationIndex == null){
			prepareRelationIndex();
		}
		
		String relations [] =relationIndex.get(type);
		if(relations == null){
			//throw new IllegalArgumentException("Not able to find related objects for type: "+ type);
		}
		return relations;
	}
	
	protected void prepareRelationIndex()
	{
		
		
		String [] catalogRelatedObjectNames = {"owner:FranchisedOutletProvinceCenter"};
		addRelationIndex("Catalog",catalogRelatedObjectNames);

		String [] levelOneCategoryRelatedObjectNames = {"catalog:Catalog"};
		addRelationIndex("LevelOneCategory",levelOneCategoryRelatedObjectNames);

		String [] levelTwoCategoryRelatedObjectNames = {"parent_category:LevelOneCategory"};
		addRelationIndex("LevelTwoCategory",levelTwoCategoryRelatedObjectNames);

		String [] levelThreeCategoryRelatedObjectNames = {"parent_category:LevelTwoCategory"};
		addRelationIndex("LevelThreeCategory",levelThreeCategoryRelatedObjectNames);

		String [] productRelatedObjectNames = {"parent_category:LevelThreeCategory"};
		addRelationIndex("Product",productRelatedObjectNames);

		String [] skuRelatedObjectNames = {"product:Product"};
		addRelationIndex("Sku",skuRelatedObjectNames);

		String [] franchisedOutletCityCenterRelatedObjectNames = {"city:FranchisedOutletCityCenter"};
		addRelationIndex("FranchisedOutletCityCenter",franchisedOutletCityCenterRelatedObjectNames);

		String [] cityCenterDepartmentRelatedObjectNames = {"city_center:FranchisedOutletCityCenter"};
		addRelationIndex("CityCenterDepartment",cityCenterDepartmentRelatedObjectNames);

		String [] cityCenterEmployeeRelatedObjectNames = {"department:CityCenterDepartment","city_center:FranchisedOutletCityCenter"};
		addRelationIndex("CityCenterEmployee",cityCenterEmployeeRelatedObjectNames);

		String [] franchisedOutletCityServiceCenterRelatedObjectNames = {"belongs_to:FranchisedOutletCityCenter"};
		addRelationIndex("FranchisedOutletCityServiceCenter",franchisedOutletCityServiceCenterRelatedObjectNames);

		String [] cityPartnerRelatedObjectNames = {"town_service_center:FranchisedOutletCityServiceCenter"};
		addRelationIndex("CityPartner",cityPartnerRelatedObjectNames);

		String [] potentialCustomerRelatedObjectNames = {"city_service_center:FranchisedOutletCityServiceCenter","city_partner:CityPartner"};
		addRelationIndex("PotentialCustomer",potentialCustomerRelatedObjectNames);

		String [] potentialCustomerContactPersonRelatedObjectNames = {"potential_customer:PotentialCustomer"};
		addRelationIndex("PotentialCustomerContactPerson",potentialCustomerContactPersonRelatedObjectNames);

		String [] potentialCustomerContactRelatedObjectNames = {"potential_customer:PotentialCustomer","city_partner:CityPartner","contact_to:PotentialCustomerContactPerson"};
		addRelationIndex("PotentialCustomerContact",potentialCustomerContactRelatedObjectNames);

		String [] cityEventRelatedObjectNames = {"city_service_center:FranchisedOutletCityServiceCenter"};
		addRelationIndex("CityEvent",cityEventRelatedObjectNames);

		String [] eventAttendanceRelatedObjectNames = {"potential_customer:PotentialCustomer","city_event:CityEvent"};
		addRelationIndex("EventAttendance",eventAttendanceRelatedObjectNames);

		String [] pageRelatedObjectNames = {"page_type:PageType","mobile_app:MobileApp"};
		addRelationIndex("Page",pageRelatedObjectNames);

		String [] pageTypeRelatedObjectNames = {"mobile_app:MobileApp"};
		addRelationIndex("PageType",pageTypeRelatedObjectNames);

		String [] slideRelatedObjectNames = {"page:Page"};
		addRelationIndex("Slide",slideRelatedObjectNames);

		String [] uiActionRelatedObjectNames = {"page:Page"};
		addRelationIndex("UiAction",uiActionRelatedObjectNames);

		String [] sectionRelatedObjectNames = {"page:Page"};
		addRelationIndex("Section",sectionRelatedObjectNames);

		String [] userWhiteListRelatedObjectNames = {"domain:UserDomain"};
		addRelationIndex("UserWhiteList",userWhiteListRelatedObjectNames);

		String [] secUserRelatedObjectNames = {"domain:UserDomain"};
		addRelationIndex("SecUser",secUserRelatedObjectNames);

		String [] userAppRelatedObjectNames = {"sec_user:SecUser"};
		addRelationIndex("UserApp",userAppRelatedObjectNames);

		String [] quickLinkRelatedObjectNames = {"app:UserApp"};
		addRelationIndex("QuickLink",quickLinkRelatedObjectNames);

		String [] listAccessRelatedObjectNames = {"app:UserApp"};
		addRelationIndex("ListAccess",listAccessRelatedObjectNames);

		String [] loginHistoryRelatedObjectNames = {"sec_user:SecUser"};
		addRelationIndex("LoginHistory",loginHistoryRelatedObjectNames);

		String [] candidateElementRelatedObjectNames = {"container:CandidateContainer"};
		addRelationIndex("CandidateElement",candidateElementRelatedObjectNames);

		String [] wechatWorkappIdentifyRelatedObjectNames = {"sec_user:SecUser"};
		addRelationIndex("WechatWorkappIdentify",wechatWorkappIdentifyRelatedObjectNames);

		String [] wechatMiniappIdentifyRelatedObjectNames = {"sec_user:SecUser"};
		addRelationIndex("WechatMiniappIdentify",wechatMiniappIdentifyRelatedObjectNames);

		String [] keypairIdentifyRelatedObjectNames = {"key_type:PublicKeyType","sec_user:SecUser"};
		addRelationIndex("KeypairIdentify",keypairIdentifyRelatedObjectNames);

		String [] publicKeyTypeRelatedObjectNames = {"domain:UserDomain"};
		addRelationIndex("PublicKeyType",publicKeyTypeRelatedObjectNames);

	
	
	}
	protected static final String TRUST_CHAIN_READ = "R";
	protected static final String TRUST_CHAIN_WRITE = "W";
	protected static final String TRUST_CHAIN_MANAGEMENT = "M";
	protected static final String TRUST_CHAIN_EXECUTION = "X";
	
	protected static final String TRUST_READ = "r";
	protected static final String TRUST_WRITE = "w";
	protected static final String TRUST_MANAGEMENT = "m";
	protected static final String TRUST_EXECUTION = "x";
	
	protected static final String TRUST_CHAIN_ALL = "MXWR";
	
	
	//small 'r','w','m','x' mean no chain trust, just trust the same level
	//default for reading trust chain, the default sequence are MXWR, the order is not affect the result
	protected void prepareRelation()
	{
		addGenericRelation("Catalog"                               ,TRUST_CHAIN_READ,"owner");
		addGenericRelation("LevelOneCategory"                      ,TRUST_CHAIN_READ,"catalog");
		addGenericRelation("LevelTwoCategory"                      ,TRUST_CHAIN_READ,"parentCategory");
		addGenericRelation("LevelThreeCategory"                    ,TRUST_CHAIN_READ,"parentCategory");
		addGenericRelation("Product"                               ,TRUST_CHAIN_READ,"parentCategory");
		addGenericRelation("Sku"                                   ,TRUST_CHAIN_READ,"product");
		addGenericRelation("FranchisedOutletCityCenter"            ,TRUST_CHAIN_READ,"city");
		addGenericRelation("CityCenterDepartment"                  ,TRUST_CHAIN_READ,"cityCenter");
		addGenericRelation("CityCenterEmployee"                    ,TRUST_CHAIN_READ,"department");
		addGenericRelation("CityCenterEmployee"                    ,TRUST_CHAIN_READ,"cityCenter");
		addGenericRelation("FranchisedOutletCityServiceCenter"     ,TRUST_CHAIN_READ,"belongsTo");
		addGenericRelation("CityPartner"                           ,TRUST_CHAIN_READ,"townServiceCenter");
		addGenericRelation("PotentialCustomer"                     ,TRUST_CHAIN_READ,"cityServiceCenter");
		addGenericRelation("PotentialCustomer"                     ,TRUST_CHAIN_READ,"cityPartner");
		addGenericRelation("PotentialCustomerContactPerson"        ,TRUST_CHAIN_READ,"potentialCustomer");
		addGenericRelation("PotentialCustomerContact"              ,TRUST_CHAIN_READ,"potentialCustomer");
		addGenericRelation("PotentialCustomerContact"              ,TRUST_CHAIN_READ,"cityPartner");
		addGenericRelation("PotentialCustomerContact"              ,TRUST_CHAIN_READ,"contactTo");
		addGenericRelation("CityEvent"                             ,TRUST_CHAIN_READ,"cityServiceCenter");
		addGenericRelation("EventAttendance"                       ,TRUST_CHAIN_READ,"potentialCustomer");
		addGenericRelation("EventAttendance"                       ,TRUST_CHAIN_READ,"cityEvent");
		addGenericRelation("Page"                                  ,TRUST_CHAIN_READ,"pageType");
		addGenericRelation("Page"                                  ,TRUST_CHAIN_READ,"mobileApp");
		addGenericRelation("PageType"                              ,TRUST_CHAIN_READ,"mobileApp");
		addGenericRelation("Slide"                                 ,TRUST_CHAIN_READ,"page");
		addGenericRelation("UiAction"                              ,TRUST_CHAIN_READ,"page");
		addGenericRelation("Section"                               ,TRUST_CHAIN_READ,"page");
		addGenericRelation("UserWhiteList"                         ,TRUST_CHAIN_READ,"domain");
		addGenericRelation("SecUser"                               ,TRUST_CHAIN_READ,"domain");
		addGenericRelation("UserApp"                               ,TRUST_CHAIN_READ,"secUser");
		addGenericRelation("QuickLink"                             ,TRUST_CHAIN_READ,"app");
		addGenericRelation("ListAccess"                            ,TRUST_CHAIN_READ,"app");
		addGenericRelation("LoginHistory"                          ,TRUST_CHAIN_READ,"secUser");
		addGenericRelation("CandidateElement"                      ,TRUST_CHAIN_READ,"container");
		addGenericRelation("WechatWorkappIdentify"                 ,TRUST_CHAIN_READ,"secUser");
		addGenericRelation("WechatMiniappIdentify"                 ,TRUST_CHAIN_READ,"secUser");
		addGenericRelation("KeypairIdentify"                       ,TRUST_CHAIN_READ,"keyType");
		addGenericRelation("KeypairIdentify"                       ,TRUST_CHAIN_READ,"secUser");
		addGenericRelation("PublicKeyType"                         ,TRUST_CHAIN_READ,"domain");
	
	}

	


}


